<?xml version="1.0" encoding="UTF-8"?><testrun name="CacheTest" project="Project 2 LRU Cache" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="CacheTest" time="0.003">
    <testcase name="testGetFileFromDataProvider2" classname="CacheTest" time="0.0"/>
    <testcase name="testGetFileFromDataProvider3" classname="CacheTest" time="0.0"/>
    <testcase name="testGetFileFromDataProvider4" classname="CacheTest" time="0.0"/>
    <testcase name="storeDataInCacheWithDataAlreadyInIt" classname="CacheTest" time="0.0"/>
    <testcase name="leastRecentlyUsedIsCorrect" classname="CacheTest" time="0.0"/>
    <testcase name="storeDataInEmptyCache" classname="CacheTest" time="0.0"/>
    <testcase name="storeDataInFullCache" classname="CacheTest" time="0.001">
      <failure>java.lang.AssertionError: expected:&lt;{0=www.youtube.com, 2=www.github.com, 4=www.facebook.com, 5=www.twitter.com}&gt; but was:&lt;{}&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at CacheTest.storeDataInFullCache(CacheTest.java:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

</failure>
    </testcase>
    <testcase name="testGetFileFromDataProvider" classname="CacheTest" time="0.0"/>
  </testsuite>
</testrun>
